name: build

on:
    push:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@v4
        - name: Remove Files
          run: rm -rf .git .vscode .github bed.zip auto.sh
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: bed
            path: ./*